config/routes.rb
WebStore::Application.routes.draw do
  resource :session
  resources :users
  resource :cart, :only => ['show', 'update']
  resource :order, :only => ['create', 'show']
  resources :products do
    #REV: it would be better if these methods used post and delete
      match "/cart/add" => "carts#add", :via => :get
      match "/cart/remove" => "carts#remove", :via => :get
  end

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy"
  match "/register" => "users#new"
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :product_id, :user_id, :quantity

  belongs_to :user
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price

  def to_dollars
    price / 100.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :password_confirmation
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :require_login

  def show
    @cart = Hash.new
    @total = 0

    session[:cart].each do |product_id, quantity|
      current = Hash.new

      current_product = Product.find(product_id)

      current["name"] = current_product.name
      current["quantity"] = quantity
      current["price"] = current_product.to_dollars
      current["line_total"] = current["price"] * quantity
    
      @total += current["line_total"]
      @cart[product_id] = current
    end
  end

  def add
    session[:cart][params[:product_id]] += 1
    flash[:cart] = "Product #{Product.find(params[:product_id]).name} added to cart"
    redirect_to products_path
  end

  def remove
    session[:cart].delete(params[:product_id])
    flash[:cart] = "Product #{Product.find(params[:product_id]).name} removed from cart"
    redirect_to cart_path
  end

  def update
    session[:cart] = Hash.new(0)
    params[:cart].each do |product_id, quantity|
      session[:cart][product_id] = quantity.to_i if quantity.to_i > 0
    end
    flash[:cart] = "Cart updated."
    redirect_to cart_path
  end

  def destroy
    session[:cart] = Hash.new(0)
  end

  private

  def require_login
    unless session[:user_id]
      flash[:error] = "You must be logged in to access this section"
      redirect_to "/login"
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    session[:cart].each do |product_id, quantity|
      Order.create!(:product_id => product_id,
                    :quantity => quantity,
                    :user_id => session[:user_id])
    end
    #REV: So are you only processing one type of product at a time? What if a user gets different items here?
    session[:cart] = Hash.new(0)
    flash[:order] = "You have placed your order! thank god we're getting rid of some of these cats."

    OrderMailer.order_confirmation(session[:user_id]).deliver

    redirect_to products_path
  end

  def show
    @orders = Order.where(:user_id => session[:user_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:user][:email])

    if !user.nil? && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      session[:cart] = Hash.new(0)
      flash[:login] = "You have logged in to the premiere cat buying site."
      redirect_to products_path
    else
      @user = User.new(:email => params[:user][:email])
      # need to refactor to use error hash instead of flash
      flash.now[:error] = "Invalid login."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to "/login"
  end

  def add_to_cart
    session[:cart] << params[:product_id]
    redirect_to products_path
  end

  #REV: Why is add_to_cart in the session controller, seems more like a products controller action.
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to new_session_url
    else
      render :new
    end
  end

  def show
  end

  #REV Doesn't look like you really need this users controller, most of this could be accomplished through sessions

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h4>cart</h4>

<% if @cart.empty? %>
  <p> Cart is empty, yo. Time to get them cats in (your cart). </p>
<% else %>

  <%= form_for(:cart, :url => cart_url, :method => :put) do |f|%>
    <ul>
      <% @cart.each do |product_id, product_details| %>
        <li>
          <input type="text" value='<%= product_details["quantity"] %>'
                 name='cart[<%=product_id%>]'>
            <%= product_details["name"]%> -- $<%= product_details["line_total"]%>
          <%= link_to "Remove", product_cart_remove_path(product_id)%>
        </li>
      <% end %>
    </ul>

    <input type="submit" value="Update Cart">
  <% end %>
    <p>Total: $<%= @total %></p>
    <!--REV:  You can use #number_to_currency here -->

  <%= form_for(:cart, :url => order_url, :method => :post) do |f|%>
    <input type="submit" value="Checkout">
  <% end %>
<% end %>
<%= link_to "<< back to products", products_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>CatStore</h1>
  <h3> the premiere online cat store</h3>

  <% if flash %>
    <% flash.each do |type, message| %>
      <div class="<%=type.to_s%>-flash"><%= message %></div>
    <% end %>
  <% end %>

  <%= yield %>

  <% if session[:user_id]%>
    <%= "Currently logged in as #{User.find(session[:user_id]).email}"%>
    <br>
    <%=link_to "Log Out", "/logout" %>
  <% end %>


</body>
</html>

app/views/orders/show.html.erb
<h3>Orders</h3>
<% @orders.each do |order|%>
  <%= "#{Product.find(order.product_id).name}: #{order.quantity}" %>
  <br>
<% end %>
<br>

app/views/products/_login_footer.html.erb
<% unless session[:user_id]%>
  <%= "You are not logged in. Please log in to shop."%>
  <br>
  <%=link_to "Log in", "/login" %>
<% end %>

app/views/products/index.html.erb
<ul>
<% @products.each do |product| %>
  <li>
   <%= link_to product.name, product_path(product)%> --
   <%= "$#{product.to_dollars}" %>
  </li>
<% end %>
</ul>

<%= link_to "view cart", cart_path%><br/>

<%= render :partial => "login_footer" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>
  <%= "$#{@product.to_dollars}" %><br />
  <% if session[:user_id]%>
    <%= link_to "Add to cart", product_cart_add_path(@product) %><br />
    <% end %>
</p>


<%= link_to "view cart", cart_path%><br />

<%= render :partial => "login_footer" %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :email %>
  <br />
  <%= f.text_field :email %>
  <br />

  <%= f.label :password %>
  <br />
  <%= f.password_field :password %>
  <br />

  <%= f.label :password_confirmation %>
  <br />
  <%= f.password_field :password_confirmation %>
  <br />

  <%= f.submit %>

<% end %>